name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

    # Pip-only installs
  - pip:
    - sphinx-autoapi
    - sphinx==6.0.0
    - numpy
    - matplotlib
    - pandas
    - https://github.com/revitron/revitron-sphinx-theme/archive/master.zip
